function writeGeoTiff(data, bbox, fileName, projection)

    TiffTags.Compression = Tiff.Compression.LZW;

%     R = maprasterref('RasterSize', size(data), ... 
%                      'YLimWorld', [bbox(2), bbox(4)], ...
%                      'XLimWorld', [bbox(1), bbox(3)], ...
%                      'ColumnsStartFrom', 'south', ... %default
%                      'RowsStartFrom', 'west'); %default
                 
    if isempty(projection)
        imwrite(data, strcat(fileName, 'tif'), 'tif', 'Compression', 'lzw');
    else
        if strcmp(projection.type, 'PROJCS')
            R = maprasterref('XLimWorld', [bbox(1), bbox(3)], ... 
                             'YLimWorld', [bbox(2), bbox(4)], ... 
                             'RasterSize', size(data), ... 
                             'RasterInterpretation', 'cells', ...
                             'ColumnsStartFrom', 'south', ...
                             'RowsStartFrom', 'west');     
            geotiffwrite(fileName, data, R, 'CoordRefSysCode', ['EPSG:', projection.id], 'TiffTags', TiffTags);       
        elseif strcmp(projection.type, 'GEOGCS')
            R = georasterref('LatitudeLimits', [bbox(2), bbox(4)], ...
                             'LongitudeLimits', [bbox(1), bbox(3)], ... 
                             'RasterSize', size(data), ...
                             'RasterInterpretation', 'cells', ...
                             'ColumnsStartFrom', 'south', ... 
                             'RowsStartFrom', 'west'); 
            geotiffwrite(fileName, data, R, 'CoordRefSysCode', ['EPSG:', projection.id], 'TiffTags', TiffTags);       
        else
            imwrite(data, strcat(fileName, 'tif'), 'tif', 'Compression', 'lzw');
        end
    end
    
end